-- =================================================================
-- SKEMA SQL LENGKAP UNTUK PROYEK FITFROMHOME
-- =================================================================
-- Jalankan kode ini di SQL Editor Supabase Anda untuk membuat semua
-- tabel dan kebijakan keamanan (RLS) yang diperlukan.
-- Disarankan untuk menjalankan setiap blok "CREATE TABLE" satu per satu.
-- =================================================================

-- =================================================================
-- Tabel 1: exercises (Perpustakaan Latihan)
-- =================================================================
CREATE TABLE public.exercises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL,
  description text,
  image_url text,
  category text,
  difficulty text,
  duration_minutes integer
);
-- Aktifkan RLS untuk tabel exercises
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Izinkan semua pengguna yang terautentikasi untuk membaca data latihan
CREATE POLICY "Allow authenticated read access to exercises"
ON public.exercises
FOR SELECT
TO authenticated
USING (true);

-- =================================================================
-- Tabel 2: recipes (Perpustakaan Resep)
-- =================================================================
CREATE TABLE public.recipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL,
  description text,
  image_url text,
  category text,
  prep_time_minutes integer,
  calories integer,
  ingredients jsonb,
  instructions text[]
);
-- Aktifkan RLS untuk tabel recipes
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Izinkan semua pengguna yang terautentikasi untuk membaca data resep
CREATE POLICY "Allow authenticated read access to recipes"
ON public.recipes
FOR SELECT
TO authenticated
USING (true);

-- =================================================================
-- Tabel 3: workout_plans (Rencana Latihan Mingguan)
-- =================================================================
CREATE TABLE public.workout_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  day_of_week smallint NOT NULL -- 1=Senin, 2=Selasa, ..., 7=Minggu
);
-- Aktifkan RLS untuk tabel workout_plans
ALTER TABLE public.workout_plans ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Izinkan semua pengguna yang terautentikasi untuk membaca rencana latihan
CREATE POLICY "Allow authenticated read access to workout plans"
ON public.workout_plans
FOR SELECT
TO authenticated
USING (true);

-- =================================================================
-- Tabel 4: workout_plan_items (Daftar Latihan per Rencana)
-- =================================================================
CREATE TABLE public.workout_plan_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id bigint NOT NULL REFERENCES public.workout_plans(id) ON DELETE CASCADE,
  exercise_id bigint NOT NULL REFERENCES public.exercises(id) ON DELETE RESTRICT,
  "order" smallint,
  sets text,
  reps text
);
-- Aktifkan RLS untuk tabel workout_plan_items
ALTER TABLE public.workout_plan_items ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Izinkan semua pengguna yang terautentikasi untuk membaca item rencana latihan
CREATE POLICY "Allow authenticated read access to workout plan items"
ON public.workout_plan_items
FOR SELECT
TO authenticated
USING (true);

-- =================================================================
-- Tabel 5: bmi_history (Riwayat Perhitungan BMI Pengguna)
-- =================================================================
CREATE TABLE public.bmi_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  weight double precision,
  height double precision,
  bmi_value double precision,
  category text
);
-- Aktifkan RLS untuk tabel bmi_history
ALTER TABLE public.bmi_history ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Pengguna hanya bisa melihat, menambah, dan menghapus riwayat BMI mereka sendiri.
CREATE POLICY "Allow individual access to own BMI history"
ON public.bmi_history
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- =================================================================
-- Tabel 6: calorie_history (Riwayat Perhitungan Kalori Pengguna)
-- =================================================================
CREATE TABLE public.calorie_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  age smallint,
  gender text,
  weight_kg double precision,
  height_cm double precision,
  activity_level text,
  bmr double precision,
  tdee double precision
);
-- Aktifkan RLS untuk tabel calorie_history
ALTER TABLE public.calorie_history ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Pengguna hanya bisa melihat, menambah, dan menghapus riwayat kalori mereka sendiri.
CREATE POLICY "Allow individual access to own calorie history"
ON public.calorie_history
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- =================================================================
-- Tabel 7: user_favorites (Item Favorit Pengguna)
-- =================================================================
CREATE TABLE public.user_favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  exercise_id bigint REFERENCES public.exercises(id) ON DELETE CASCADE,
  recipe_id bigint REFERENCES public.recipes(id) ON DELETE CASCADE
);
-- Aktifkan RLS untuk tabel user_favorites
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;
-- Kebijakan: Pengguna hanya bisa melihat, menambah, dan menghapus item favorit mereka sendiri.
CREATE POLICY "Allow individual access to own favorites"
ON public.user_favorites
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

